SET NOCOUNT ON

INSERT INTO RESEARCH.EMPLOYEE(ID, JOBID, FNAME, LNAME, SOCIAL_SECURITY, LongText)
SELECT NEXT VALUE FOR RESEARCH.SEQ_EMPLOYEE, NULL, NEWID(), NEWID(), NEWID(), REPLICATE(NEWID(),2)
GO 10


-- INSERT INTO RESEARCH.JOB
-- SELECT NEXT VALUE FOR RESEARCH.SEQ_JOB, 