-- Connection 2
USE TestDB
GO
SELECT NAME, OBJECTPROPERTY(object_id,'TableIsMemoryOptimized') IsMemoryOptimized FROM sys.tables WHERE name = 'SampleData'

BEGIN TRY
	BEGIN TRAN
		-- Step: 2
		UPDATE dbo.SampleData_SCHEMA_AND_DATA
		SET StateID = 'BB'
		WHERE ID = 1

		-- Step: 4
		UPDATE dbo.SampleData_SCHEMA_AND_DATA
		SET StateID = 'BB'
		WHERE ID = 2
	--COMMIT
END TRY
BEGIN CATCH
	SELECT ERROR_LINE, ERROR_MESSAGE, ERROR_NUMBER, ERROR_PROCEDURE, ERROR_SEVERITY, ERROR_STATE
END CATCH
ROLLBACK