CREATE SCHEMA RESEARCH;
GO
CREATE SEQUENCE RESEARCH.SEQ_EMPLOYEE START WITH 1 INCREMENT BY 1
CREATE SEQUENCE RESEARCH.SEQ_JOB START WITH 1 INCREMENT BY 1
CREATE TABLE RESEARCH.EMPLOYEE
(
        ID INT NOT NULL PRIMARY KEY, 	JOBID INT NULL, 	FNAME NVARCHAR(100) NOT NULL, 
		LNAME NVARCHAR(100) NOT NULL, 	SOCIAL_SECURITY NVARCHAR(100) NOT NULL, 
		LongText NVARCHAR(MAX) NULL
)

CREATE TABLE RESEARCH.JOB
(
        ID INT PRIMARY KEY NOT NULL, 
		JOB_NAME NVARCHAR(100), 
        LongText NVARCHAR(MAX)
)


CREATE SEQUENCE RESEARCH.SEQ_EMPLOYEE_NC START WITH 1 INCREMENT BY 1
CREATE SEQUENCE RESEARCH.SEQ_JOB_NC START WITH 1 INCREMENT BY 1
CREATE TABLE RESEARCH.EMPLOYEE_NC
(
        ID INT NOT NULL, 	JOBID INT NULL, 	FNAME NVARCHAR(100) NOT NULL, 
		LNAME NVARCHAR(100) NOT NULL, 			SOCIAL_SECURITY NVARCHAR(100) NOT NULL, 
		LongText NVARCHAR(MAX) NULL
)

ALTER TABLE RESEARCH.EMPLOYEE_NC ADD CONSTRAINT PK_RESEARCH_EMPLOYEE_NC_ID PRIMARY KEY NONCLUSTERED (ID)

CREATE TABLE RESEARCH.JOB_NC
(
        ID INT NOT NULL, 
		JOB_NAME NVARCHAR(100), 
        LongText NVARCHAR(MAX)
)

ALTER TABLE RESEARCH.JOB_NC ADD CONSTRAINT PK_RESEARCH_JOB_NC_ID PRIMARY KEY NONCLUSTERED (ID)


CREATE SEQUENCE RESEARCH.SEQ_EMPLOYEE_GUID START WITH 1 INCREMENT BY 1
CREATE TABLE RESEARCH.EMPLOYEE_GUID(
	ID UNIQUEIDENTIFIER NOT NULL PRIMARY KEY, 	JOBID INT NULL, 		FNAME NVARCHAR(100) NOT NULL, 
	LNAME NVARCHAR(100) NOT NULL, 				SOCIAL_SECURITY NVARCHAR(100) NOT NULL, 
	LongText NVARCHAR(MAX) NULL
)

CREATE SEQUENCE RESEARCH.SEQ_EMPLOYEE_GUID_NC START WITH 1 INCREMENT BY 1
CREATE TABLE RESEARCH.EMPLOYEE_GUID_NC(
	ID UNIQUEIDENTIFIER NOT NULL, 			JOBID INT NULL, 			FNAME NVARCHAR(100) NOT NULL, 
	LNAME NVARCHAR(100) NOT NULL, 			SOCIAL_SECURITY NVARCHAR(100) NOT NULL, 
	LongText NVARCHAR(MAX) NULL
)
ALTER TABLE RESEARCH.EMPLOYEE_GUID_NC ADD CONSTRAINT PK_RESEARCH_EMPLOYEE_GUID_NC PRIMARY KEY NONCLUSTERED (ID)

CREATE TABLE RESEARCH.EMPLOYEE_GUID_ORDERED(
	ID UNIQUEIDENTIFIER NOT NULL PRIMARY KEY, 	JOBID INT NULL, 			FNAME NVARCHAR(100) NOT NULL, 
	LNAME NVARCHAR(100) NOT NULL, 				SOCIAL_SECURITY NVARCHAR(100) NOT NULL, 
	LongText NVARCHAR(MAX) NULL
)

CREATE TABLE RESEARCH.EMPLOYEE_GUID_ORDERED_NC(
	ID UNIQUEIDENTIFIER NOT NULL, 				JOBID INT NULL, 			FNAME NVARCHAR(100) NOT NULL, 
	LNAME NVARCHAR(100) NOT NULL, 				SOCIAL_SECURITY NVARCHAR(100) NOT NULL, 
	LongText NVARCHAR(MAX) NULL
)
ALTER TABLE RESEARCH.EMPLOYEE_GUID_ORDERED_NC ADD CONSTRAINT PK_RESEARCH_EMPLOYEE_GUID_ORDERED_NC PRIMARY KEY NONCLUSTERED (ID)

IF OBJECT_ID('RESEARCH.uspSingleRowSelect', 'P') IS NOT NULL
BEGIN
	DROP PROCEDURE RESEARCH.uspSingleRowSelect
END

GO

CREATE PROCEDURE RESEARCH.uspSingleRowSelect(@firstNum INT, @lastNum INT) AS
BEGIN
	SET NOCOUNT ON
	BEGIN TRY
		WHILE @firstNum <= @lastNum
		BEGIN
			SELECT * 
			FROM RESEARCH.EMPLOYEE 
			WHERE ID = (SELECT 1+ CONVERT(INT, (1000-1+1)*RAND())) -- Random ID
			ORDER BY FNAME, LNAME
			SET @firstNum += 1
		END
	END TRY
	BEGIN CATCH
	END CATCH
END

GO

IF OBJECT_ID('RESEARCH.uspSingleRowSelect_NC', 'P') IS NOT NULL
BEGIN
	DROP PROCEDURE RESEARCH.uspSingleRowSelect_NC
END

GO

CREATE PROCEDURE RESEARCH.uspSingleRowSelect_NC(@firstNum INT, @lastNum INT) AS
BEGIN
	SET NOCOUNT ON
	BEGIN TRY
		WHILE @firstNum <= @lastNum
		BEGIN
			SELECT * 
			FROM RESEARCH.EMPLOYEE_NC 
			WHERE ID = (SELECT 1+ CONVERT(INT, (1000-1+1)*RAND())) -- Random ID
			ORDER BY FNAME, LNAME
			SET @firstNum += 1
		END
	END TRY
	BEGIN CATCH
	END CATCH
END