USE dbtest
GO
CREATE SCHEMA RESEARCH;
GO
CREATE SEQUENCE RESEARCH.SEQ_EMPLOYEE START WITH 1 INCREMENT BY 1
CREATE SEQUENCE RESEARCH.SEQ_JOB START WITH 1 INCREMENT BY 1
CREATE TABLE RESEARCH.EMPLOYEE
(
        ID INT NOT NULL PRIMARY KEY, JOBID INT NULL, FNAME NVARCHAR(100) NOT NULL, LNAME NVARCHAR(100) NOT NULL, 
        SOCIAL_SECURITY NVARCHAR(100) NOT NULL, LongText NVARCHAR(MAX) NULL
)

CREATE TABLE RESEARCH.JOB
(
        ID INT PRIMARY KEY NOT NULL, JOB_NAME NVARCHAR(100), 
        LongText NVARCHAR(MAX)
)

