USE master 
GO
IF db_id('dbtest') IS NOT NULL
BEGIN
    PRINT 'Dropping database dbtest'
    DROP DATABASE dbtest
END

CREATE DATABASE dbtest
GO
ALTER DATABASE dbtest SET ALLOW_SNAPSHOT_ISOLATION ON 
ALTER DATABASE [dbtest] SET READ_COMMITTED_SNAPSHOT OFF WITH NO_WAIT

USE dbtest
GO
CREATE SCHEMA RESEARCH;
GO
CREATE SEQUENCE RESEARCH.SEQ_EMPLOYEE START WITH 1 INCREMENT BY 1
CREATE SEQUENCE RESEARCH.SEQ_JOB START WITH 1 INCREMENT BY 1
CREATE TABLE RESEARCH.EMPLOYEE
(
        ID INT NOT NULL PRIMARY KEY, JOBID INT NULL, FNAME NVARCHAR(100) NOT NULL, LNAME NVARCHAR(100) NOT NULL, 
        SOCIAL_SECURITY NVARCHAR(100) NOT NULL, LongText NVARCHAR(MAX) NULL
)

CREATE TABLE RESEARCH.JOB
(
        ID INT PRIMARY KEY NOT NULL, JOB_NAME NVARCHAR(100), 
        LongText NVARCHAR(MAX)
)


USE dbtest
GO
SET NOCOUNT ON

INSERT INTO RESEARCH.EMPLOYEE(ID, JOBID, FNAME, LNAME, SOCIAL_SECURITY, LongText)
SELECT NEXT VALUE FOR RESEARCH.SEQ_EMPLOYEE, NULL, NEWID(), NEWID(), NEWID(), REPLICATE(NEWID(),2)
GO 10


-- INSERT INTO RESEARCH.JOB
-- SELECT NEXT VALUE FOR RESEARCH.SEQ_JOB, 
