
SELECT 
       SERVERPROPERTY('BuildClrVersion') BuildClrVersion,
       SERVERPROPERTY('Collation') Collation, 
       SERVERPROPERTY('CollationID') CollationID,
       SERVERPROPERTY('ComparisonStyle') ComparisonStyle,
       SERVERPROPERTY('ComputerNamePhysicalNetBIOS') ComputerNamePhysicalNetBIOS,
       SERVERPROPERTY('Edition') Edition,
       SERVERPROPERTY('EditionID') EditionID,
       SERVERPROPERTY('EngineEdition') EngineEdition,
       SERVERPROPERTY('InstanceName') InstanceName,
       SERVERPROPERTY('IsClustered') IsClustered,
       SERVERPROPERTY('IsFullTextInstalled') IsFullTextInstalled,
       SERVERPROPERTY('IsIntegratedSecurityOnly') IsIntegratedSecurityOnly,
       SERVERPROPERTY('IsSingleUser') IsSingleUser,
       SERVERPROPERTY('LCID') LCID,
       SERVERPROPERTY('LicenseType') LicenseType,
       SERVERPROPERTY('MachineName') MachineName,
       SERVERPROPERTY('NumLicenses') NumLicenses,
       SERVERPROPERTY('ProcessID') ProcessID,
       SERVERPROPERTY('ProductVersion') ProductVersion,
       SERVERPROPERTY('ProductLevel') ProductLevel,
       SERVERPROPERTY('ResourceLastUpdateDateTime') ResourceLastUpdateDateTime,
       SERVERPROPERTY('ResourceVersion') ResourceVersion,
       SERVERPROPERTY('ServerName') ServerName,
       SERVERPROPERTY('SqlCharSet') SqlCharSet,
       SERVERPROPERTY('SqlCharSetName') SqlCharSetName,
       SERVERPROPERTY('SqlSortOrder') SqlSortOrder,
       SERVERPROPERTY('SqlSortOrderName')SqlSortOrderName,
       (SELECT windows_release from sys.dm_os_windows_info) WindowsReleaseNumber,
	   (SELECT windows_service_pack_level from sys.dm_os_windows_info) WindowsServicePack, 
	   (SELECT system_memory_state_desc FROM sys.dm_os_sys_memory) SystemMemoryStateDesc,
	   (SELECT cpu_count FROM sys.dm_os_sys_info) CpuCount,
	   (SELECT affinity_type_desc FROM sys.dm_os_sys_info) AffinityMask,
	   (SELECT hyperthread_ratio FROM sys.dm_os_sys_info) HyperthreadRation,
	   (SELECT (physical_memory_in_bytes / 1024 / 1024) FROM sys.dm_os_sys_info) PhysicalMemoryMB,
	   (select sqlserver_start_time FROM sys.dm_os_sys_info) SQLServerStartTime,
	   (SELECT virtual_machine_type_desc FROM sys.dm_os_sys_info) VirtualizationType
