USE clusteredIndexAnalysis
GO

SET STATISTICS IO ON
exec RESEARCH.uspSingleRowSelect @firstNum=1, @lastNum=1
exec RESEARCH.uspSingleRowSelect_NC @firstNum=1, @lastNum=1 

SELECT * 
FROM RESEARCH.EMPLOYEE 
WHERE ID = (SELECT 1+ CONVERT(INT, (1000-1+1)*RAND())) -- Random ID
ORDER BY FNAME, LNAME

SELECT * 
FROM RESEARCH.EMPLOYEE_NC
WHERE ID = (SELECT 1+ CONVERT(INT, (1000-1+1)*RAND())) -- Random ID
ORDER BY FNAME, LNAME

SELECT * 
FROM RESEARCH.EMPLOYEE_GUID
WHERE ID = '38B8BA63-BB49-49CD-889E-7B636E23B575' -- Requires a manual change to this value 
ORDER BY FNAME, LNAME

SELECT * 
FROM RESEARCH.EMPLOYEE_GUID_NC
WHERE ID = '6C198C64-AB87-44B7-BE7D-B5D062CBCD8F' -- Requires a manual change to this value 
ORDER BY FNAME, LNAME