IF db_id('clusteredIndexAnalysis') IS NOT NULL
BEGIN
    PRINT 'Dropping database clusteredIndexAnalysis'
    DROP DATABASE clusteredIndexAnalysis
END

CREATE DATABASE clusteredIndexAnalysis
GO
ALTER DATABASE clusteredIndexAnalysis SET ALLOW_SNAPSHOT_ISOLATION ON
ALTER DATABASE clusteredIndexAnalysis SET READ_COMMITTED_SNAPSHOT OFF



USE [master]
GO
ALTER DATABASE [clusteredIndexAnalysis] SET QUERY_STORE = ON
GO
ALTER DATABASE [clusteredIndexAnalysis] SET QUERY_STORE (OPERATION_MODE = READ_ONLY, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 99), DATA_FLUSH_INTERVAL_SECONDS = 60, INTERVAL_LENGTH_MINUTES = 1, MAX_STORAGE_SIZE_MB = 10240, SIZE_BASED_CLEANUP_MODE = OFF)
GO
