SET NOCOUNT ON

INSERT INTO RESEARCH.EMPLOYEE(ID, JOBID, FNAME, LNAME, SOCIAL_SECURITY, LongText)
SELECT NEXT VALUE FOR RESEARCH.SEQ_EMPLOYEE, NULL, NEWID(), NEWID(), NEWID(), REPLICATE(NEWID(),2)
FROM sys.columns a, (SELECT TOP 300 * from sys.columns ) b
GO 10


INSERT INTO RESEARCH.EMPLOYEE_NC(ID, JOBID, FNAME, LNAME, SOCIAL_SECURITY, LongText)
SELECT NEXT VALUE FOR RESEARCH.SEQ_EMPLOYEE_NC, NULL, NEWID(), NEWID(), NEWID(), REPLICATE(NEWID(),2)
FROM sys.columns a, (SELECT TOP 300 * from sys.columns ) b
GO 10


INSERT INTO RESEARCH.EMPLOYEE_GUID(ID, JOBID, FNAME, LNAME, SOCIAL_SECURITY, LongText)
SELECT NEWID(), NULL, NEWID(), NEWID(), NEWID(), REPLICATE(NEWID(),2)
FROM sys.columns a, (SELECT TOP 300 * from sys.columns ) b
GO 10

INSERT INTO RESEARCH.EMPLOYEE_GUID_NC(ID, JOBID, FNAME, LNAME, SOCIAL_SECURITY, LongText)
SELECT NEWID(), NULL, NEWID(), NEWID(), NEWID(), REPLICATE(NEWID(),2)
FROM sys.columns a, (SELECT TOP 300 * from sys.columns ) b
GO 10

-- INSERT INTO RESEARCH.JOB
-- SELECT NEXT VALUE FOR RESEARCH.SEQ_JOB, 