USE clusteredIndexAnalysis
GO

SET STATISTICS IO ON
--exec RESEARCH.uspSingleRowSelect @firstNum=1, @lastNum=1
--exec RESEARCH.uspSingleRowSelect_NC @firstNum=1, @lastNum=1 

SELECT * 
FROM RESEARCH.EMPLOYEE 
WHERE ID = (SELECT 1+ CONVERT(INT, (1000-1+1)*RAND())) -- Random ID
ORDER BY FNAME, LNAME

SELECT * 
FROM RESEARCH.EMPLOYEE_NC
WHERE ID = (SELECT 1+ CONVERT(INT, (1000-1+1)*RAND())) -- Random ID
ORDER BY FNAME, LNAME

SELECT * 
FROM RESEARCH.EMPLOYEE_GUID
WHERE ID = 'C44DC2A9-8A17-40EF-AC5B-8155745747EF' -- Requires a manual change to this value 
ORDER BY FNAME, LNAME

SELECT * 
FROM RESEARCH.EMPLOYEE_GUID_NC
WHERE ID = 'E8319E40-266E-402D-9F4B-264D46C5970C' -- Requires a manual change to this value 
ORDER BY FNAME, LNAME